/**
 * Expanded Stage 1 evaluation pairs for MiniLM-L6-v2 cosine similarity.
 *
 * This file intentionally broadens the original 43-pair calibration set with
 * a larger mix of realistic goal/page combinations so we can probe how the
 * current title+URL-only thresholds behave on harder, more varied cases.
 */

import type { ThresholdPair } from './threshold-pairs';

type PairSeed = Omit<ThresholdPair, 'goal'>;

const buildGoalPairs = (goal: string, pairs: PairSeed[]): ThresholdPair[] =>
  pairs.map((pair) => ({ goal, ...pair }));

const biologyPairs = buildGoalPairs('study for biology exam', [
  {
    pageTitle: 'Khan Academy | Cell Division and the Cell Cycle',
    pageUrl: 'https://www.khanacademy.org/science/biology/cellular-molecular-biology/mitosis/v/phases-of-mitosis',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Mitosis and Meiosis - Biology LibreTexts',
    pageUrl: 'https://bio.libretexts.org/Bookshelves/Introductory_and_General_Biology/mitosis-meiosis',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Crash Course Biology #12 - DNA Structure and Replication',
    pageUrl: 'https://www.youtube.com/watch?v=8kK2zwjRV0M',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'OpenStax Biology 2e - Cell Structure',
    pageUrl: 'https://openstax.org/books/biology-2e/pages/4-introduction',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'ESPN - NBA Scores, Stats & Highlights',
    pageUrl: 'https://www.espn.com/nba/scoreboard',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Netflix - Trending Now',
    pageUrl: 'https://www.netflix.com/browse',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Funny Cat Videos Compilation 2026',
    pageUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Amoeba Sisters - Enzymes (Updated)',
    pageUrl: 'https://www.youtube.com/watch?v=qgVFkRn8f10',
    expectedLabel: 'on-task',
    category: 'tricky',
    note: 'YouTube but clearly biology content.',
  },
  {
    pageTitle: 'Cellular Respiration - NCBI',
    pageUrl: 'https://www.ncbi.nlm.nih.gov/books/NBK21582/',
    expectedLabel: 'on-task',
    category: 'tricky',
    note: 'Dense reference material, but directly relevant.',
  },
  {
    pageTitle: 'Biology flashcards - Quizlet',
    pageUrl: 'https://quizlet.com/biology',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'OpenStax Biology 2e - Genetics and Heredity',
    pageUrl: 'https://openstax.org/books/biology-2e/pages/13-introduction',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Taylor Swift - Biography, Songs & Albums',
    pageUrl: 'https://en.wikipedia.org/wiki/Taylor_Swift',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: '"bio" substring false positive.',
  },
  {
    pageTitle: 'r/biology - help me pick a science tattoo design',
    pageUrl: 'https://www.reddit.com/r/biology/comments/abc123/help_me_pick_a_science_tattoo',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'Keyword overlap with a social page.',
  },
  {
    pageTitle: 'Biography of Marie Curie - Britannica',
    pageUrl: 'https://www.britannica.com/biography/Marie-Curie',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Biology memes for students - Reddit',
    pageUrl: 'https://www.reddit.com/r/funny/comments/biology_memes_students',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Google Docs - Untitled document',
    pageUrl: 'https://docs.google.com/document/d/1aBcDeFgHiJkLmNoPqRsTuVwXyZ/edit',
    expectedLabel: 'borderline',
    category: 'borderline',
    note: 'Writing space without a subject signal.',
  },
  {
    pageTitle: 'Notion - Biology exam plan',
    pageUrl: 'https://www.notion.so/biology-exam-plan',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'AnkiWeb - Biology deck',
    pageUrl: 'https://ankiweb.net/shared/info/biology-deck',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'OneNote - Lab notes',
    pageUrl: 'https://www.onenote.com/notebooks/biology-lab-notes',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Google Sheets - Study tracker',
    pageUrl: 'https://docs.google.com/spreadsheets/d/biology-study-tracker',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Quizlet - Chapter 5 flashcards',
    pageUrl: 'https://quizlet.com/biology/chapter-5',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
]);

const reactPairs = buildGoalPairs('build a React todo app', [
  {
    pageTitle: 'Tutorial: Tic-Tac-Toe - React',
    pageUrl: 'https://react.dev/learn/tutorial-tic-tac-toe',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'useState - React Reference',
    pageUrl: 'https://react.dev/reference/react/useState',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Thinking in React',
    pageUrl: 'https://react.dev/learn/thinking-in-react',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'State: A Component\'s Memory - React',
    pageUrl: 'https://react.dev/learn/state-a-components-memory',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Amazon.com: Today\'s Deals - Electronics, Home, Fashion',
    pageUrl: 'https://www.amazon.com/deals',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Wordle - A daily word game - The New York Times',
    pageUrl: 'https://www.nytimes.com/games/wordle/index.html',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Instagram',
    pageUrl: 'https://www.instagram.com/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'How to Use Zustand for State Management in React',
    pageUrl: 'https://blog.logrocket.com/zustand-react-state-management/',
    expectedLabel: 'on-task',
    category: 'tricky',
    note: 'State library is useful for a todo app.',
  },
  {
    pageTitle: 'A Complete Guide to Flexbox - CSS-Tricks',
    pageUrl: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'javascript - How to use Array.map() to render a list of items',
    pageUrl: 'https://stackoverflow.com/questions/123456/how-to-use-array-map-to-render-list',
    expectedLabel: 'on-task',
    category: 'tricky',
    note: 'Generic JS utility, but directly relevant to rendering todo lists.',
  },
  {
    pageTitle: 'React todo app starter - GitHub',
    pageUrl: 'https://github.com/example/react-todo-starter',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Setting up the development environment - React Native',
    pageUrl: 'https://reactnative.dev/docs/environment-setup',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'React keyword, but wrong platform.',
  },
  {
    pageTitle: 'Angular vs React vs Vue.js - Which Framework to Choose in 2026',
    pageUrl: 'https://www.techradar.com/best/javascript-frameworks-comparison',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'Comparison shopping, not building.',
  },
  {
    pageTitle: 'Next.js App Router docs',
    pageUrl: 'https://nextjs.org/docs/app',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Redux Toolkit - Essentials',
    pageUrl: 'https://redux-toolkit.js.org/tutorials/essentials/part-1-overview-concepts',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'CodeSandbox - Create and share web apps',
    pageUrl: 'https://codesandbox.io/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'StackBlitz - Instant dev environments',
    pageUrl: 'https://stackblitz.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Storybook - Component explorer',
    pageUrl: 'https://storybook.js.org/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Figma - Todo app inspiration',
    pageUrl: 'https://www.figma.com/community/search?query=todo%20app',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'MDN Web Docs - Array methods',
    pageUrl: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'GitHub Gist - Snippets',
    pageUrl: 'https://gist.github.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
]);

const jobsPairs = buildGoalPairs('apply for software engineering jobs', [
  {
    pageTitle: 'Software Engineer - Google Careers',
    pageUrl: 'https://careers.google.com/jobs/results/123456-software-engineer',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Software Engineer Jobs - LinkedIn',
    pageUrl: 'https://www.linkedin.com/jobs/search/?keywords=software+engineer',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Software Engineer Resume Guide - Indeed',
    pageUrl: 'https://www.indeed.com/career-advice/resumes-cover-letters/software-engineer-resume',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Software Engineer - Workday application',
    pageUrl: 'https://myworkdayjobs.com/software-engineer/apply',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Steam Store - Featured & Recommended Games',
    pageUrl: 'https://store.steampowered.com/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Instagram',
    pageUrl: 'https://www.instagram.com/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Funny Cat Videos Compilation 2026',
    pageUrl: 'https://www.youtube.com/watch?v=catvideos2026',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Software Engineer Salaries at Google - Glassdoor',
    pageUrl: 'https://www.glassdoor.com/Salary/Google-Software-Engineer-Salaries-E9079.htm',
    expectedLabel: 'on-task',
    category: 'tricky',
    note: 'Salary research is part of job hunting.',
  },
  {
    pageTitle: 'Resume templates for software engineers',
    pageUrl: 'https://www.canva.com/resumes/templates/software-engineer/',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Cover letter guide for engineers',
    pageUrl: 'https://www.themuse.com/advice/how-to-write-a-cover-letter',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'GitHub profile - ashrafur',
    pageUrl: 'https://github.com/ashrafur',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'LeetCode - Two Sum',
    pageUrl: 'https://leetcode.com/problems/two-sum/',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'Interview prep, not the application flow itself.',
  },
  {
    pageTitle: 'HackerRank - Coding Practice',
    pageUrl: 'https://www.hackerrank.com/domains/tutorials/10-days-of-javascript',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Interviewing.io - Mock interviews',
    pageUrl: 'https://interviewing.io/',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Cracking the Coding Interview companion site',
    pageUrl: 'https://www.crackingthecodinginterview.com/',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'LinkedIn Home',
    pageUrl: 'https://www.linkedin.com/feed/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Notion - Job application tracker',
    pageUrl: 'https://www.notion.so/job-application-tracker',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Google Docs - Resume draft',
    pageUrl: 'https://docs.google.com/document/d/resume-draft',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Gmail inbox',
    pageUrl: 'https://mail.google.com/mail/u/0/#inbox',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Calendly - Networking call',
    pageUrl: 'https://calendly.com/networking-call',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Google Drive - Portfolio folder',
    pageUrl: 'https://drive.google.com/drive/folders/portfolio',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
]);

const climatePairs = buildGoalPairs('write research paper on climate change', [
  {
    pageTitle: 'NASA - Climate Change: Vital Signs of the Planet',
    pageUrl: 'https://climate.nasa.gov/vital-signs/',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'climate change impacts - Google Scholar',
    pageUrl: 'https://scholar.google.com/scholar?q=climate+change+impacts',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'IPCC Sixth Assessment Report',
    pageUrl: 'https://www.ipcc.ch/report/ar6/syr/',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'JSTOR - climate adaptation',
    pageUrl: 'https://www.jstor.org/action/doBasicSearch?Query=climate%20adaptation',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Netflix - Trending Now',
    pageUrl: 'https://www.netflix.com/browse',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Home / X',
    pageUrl: 'https://x.com/home',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Reddit - Funny memes',
    pageUrl: 'https://www.reddit.com/r/funny/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Google Docs - Climate paper outline',
    pageUrl: 'https://docs.google.com/document/d/climate-paper-outline/edit',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Zotero library',
    pageUrl: 'https://www.zotero.org/users/local/climate-library',
    expectedLabel: 'on-task',
    category: 'tricky',
    note: 'Research workflow tool.',
  },
  {
    pageTitle: 'Overleaf project',
    pageUrl: 'https://www.overleaf.com/project/climate-paper',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'ScienceDirect - Climate emissions article',
    pageUrl: 'https://www.sciencedirect.com/science/article/pii/S1234567890',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Climate change memes - r/funny',
    pageUrl: 'https://www.reddit.com/r/funny/comments/climate_change_memes',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'Keyword overlap, but it is meme browsing.',
  },
  {
    pageTitle: 'Weather app',
    pageUrl: 'https://weather.com/',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'The Climate Pledge Arena - Home',
    pageUrl: 'https://climatepledgearena.com/',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Climate legislation news roundup',
    pageUrl: 'https://www.npr.org/climate-news-roundup',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'News reading, not paper research.',
  },
  {
    pageTitle: 'Grammarly - Free AI Writing Assistance',
    pageUrl: 'https://app.grammarly.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Mendeley',
    pageUrl: 'https://www.mendeley.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Notion - Research notes',
    pageUrl: 'https://www.notion.so/research-notes',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Google Drive - Literature folder',
    pageUrl: 'https://drive.google.com/drive/folders/literature',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Citation style guide',
    pageUrl: 'https://libguides.example.edu/citation-style-guide',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Data extraction spreadsheet',
    pageUrl: 'https://docs.google.com/spreadsheets/d/climate-data-extraction',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
]);

const spanishPairs = buildGoalPairs('learn Spanish on Duolingo', [
  {
    pageTitle: 'Duolingo - Learn Spanish for Free',
    pageUrl: 'https://www.duolingo.com/learn',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'SpanishDict | English to Spanish Translation, Dictionary, Conjugation',
    pageUrl: 'https://www.spanishdict.com/translate/hello',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'BBC Mundo - Spanish lessons',
    pageUrl: 'https://www.bbc.com/mundo',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Conjuguemos - Spanish grammar practice',
    pageUrl: 'https://conjuguemos.com/',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'TikTok - Make Your Day',
    pageUrl: 'https://www.tiktok.com/foryou',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Twitch - Live Gaming & Esports Streams',
    pageUrl: 'https://www.twitch.tv/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Netflix - Trending Now',
    pageUrl: 'https://www.netflix.com/browse',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Beginner Spanish listening practice - YouTube',
    pageUrl: 'https://www.youtube.com/watch?v=span456',
    expectedLabel: 'on-task',
    category: 'tricky',
    note: 'YouTube, but still a study resource.',
  },
  {
    pageTitle: 'Conjugation of "ser" - 123TeachMe',
    pageUrl: 'https://www.123teachme.com/spanish_verb_conjugation/ser',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Anki - Spanish vocab deck',
    pageUrl: 'https://ankiweb.net/shared/info/spanish-vocab',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Quizlet - Spanish flashcards',
    pageUrl: 'https://quizlet.com/spanish',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Google Translate',
    pageUrl: 'https://translate.google.com/?sl=en&tl=es',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'Translation tool, not the learning session itself.',
  },
  {
    pageTitle: 'Spanish football highlights',
    pageUrl: 'https://www.youtube.com/watch?v=spanish-football',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'r/Spanish - meme thread',
    pageUrl: 'https://www.reddit.com/r/Spanish/comments/meme_thread',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Barcelona tapas travel blog',
    pageUrl: 'https://www.nomadicmatt.com/travel-blogs/barcelona-tapas/',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'Spanish keyword, but travel browsing.',
  },
  {
    pageTitle: 'Memrise dashboard',
    pageUrl: 'https://www.memrise.com/dashboard',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'HelloTalk chat',
    pageUrl: 'https://www.hellotalk.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'LingQ lesson queue',
    pageUrl: 'https://www.lingq.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Language exchange Discord',
    pageUrl: 'https://discord.com/channels/language-exchange',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Duolingo forums',
    pageUrl: 'https://forum.duolingo.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Clozemaster statistics',
    pageUrl: 'https://www.clozemaster.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
]);

const japanTripPairs = buildGoalPairs('plan a trip to Japan', [
  {
    pageTitle: 'Google Flights - Tokyo',
    pageUrl: 'https://www.google.com/travel/flights',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Airbnb - Tokyo stay',
    pageUrl: 'https://www.airbnb.com/s/Tokyo--Japan/homes',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Japan Travel Bureau - itinerary ideas',
    pageUrl: 'https://www.japan.travel/en/plan/',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Booking.com - Tokyo hotels',
    pageUrl: 'https://www.booking.com/city/jp/tokyo.html',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Netflix - Trending Now',
    pageUrl: 'https://www.netflix.com/browse',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Steam Store - Featured & Recommended Games',
    pageUrl: 'https://store.steampowered.com/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Instagram',
    pageUrl: 'https://www.instagram.com/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Japan Rail Pass guide',
    pageUrl: 'https://www.japanrailpass-reservation.com/',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Google Maps - Tokyo Station',
    pageUrl: 'https://www.google.com/maps/place/Tokyo+Station',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Google Travel - itinerary draft',
    pageUrl: 'https://www.google.com/travel/',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Weather in Tokyo',
    pageUrl: 'https://weather.com/weather/today/l/Tokyo+Japan',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Japanese cooking vlog',
    pageUrl: 'https://www.youtube.com/watch?v=japanese-cooking',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Japanese language app lesson',
    pageUrl: 'https://app.duolingo.com/learn-japanese',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'Useful adjacent learning, but not the travel planning goal.',
  },
  {
    pageTitle: 'Japan baseball highlights',
    pageUrl: 'https://www.youtube.com/watch?v=japan-baseball',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Japanese knife set on Amazon',
    pageUrl: 'https://www.amazon.com/s?k=japanese+knife+set',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Google Docs - Trip itinerary',
    pageUrl: 'https://docs.google.com/document/d/japan-itinerary/edit',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'TripIt',
    pageUrl: 'https://www.tripit.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Rome2Rio',
    pageUrl: 'https://www.rome2rio.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'XE currency converter',
    pageUrl: 'https://www.xe.com/currencyconverter/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Google Maps - Saved places',
    pageUrl: 'https://www.google.com/maps/saved',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Booking.com wishlist',
    pageUrl: 'https://www.booking.com/mywishlist.html',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
]);

const taxesPairs = buildGoalPairs('file my taxes for 2026', [
  {
    pageTitle: 'IRS Free File',
    pageUrl: 'https://www.irs.gov/filing/free-file-do-your-federal-taxes-for-free',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'TurboTax - Start your return',
    pageUrl: 'https://turbotax.intuit.com/personal-taxes/online/',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'H&R Block - Log in',
    pageUrl: 'https://www.hrblock.com/login/',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'IRS withholding estimator',
    pageUrl: 'https://www.irs.gov/individuals/tax-withholding-estimator',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'YouTube - Funny cat videos',
    pageUrl: 'https://www.youtube.com/watch?v=catvideos2026',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Amazon.com',
    pageUrl: 'https://www.amazon.com/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Home / X',
    pageUrl: 'https://x.com/home',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'W-2 instructions',
    pageUrl: 'https://www.irs.gov/forms-pubs/about-form-w-2',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: '1099-NEC explanation',
    pageUrl: 'https://www.irs.gov/forms-pubs/about-form-1099-nec',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Schedule C instructions',
    pageUrl: 'https://www.irs.gov/forms-pubs/about-schedule-c-form-1040',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Taxonomy of flowering plants - Britannica',
    pageUrl: 'https://www.britannica.com/science/taxonomy',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: '"tax" prefix overlap with taxonomy.',
  },
  {
    pageTitle: 'Taxidermy techniques - museum blog',
    pageUrl: 'https://www.examplemuseum.org/blog/taxidermy-techniques',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Tax collector movie trailer',
    pageUrl: 'https://www.youtube.com/watch?v=tax-collector-trailer',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Tax reform news podcast',
    pageUrl: 'https://podcasts.apple.com/us/podcast/tax-reform-news',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Google Sheets - Expense tracker',
    pageUrl: 'https://docs.google.com/spreadsheets/d/expense-tracker',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Bank statements PDF',
    pageUrl: 'https://www.chase.com/bank-statements.pdf',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Receipt scan folder',
    pageUrl: 'https://drive.google.com/drive/folders/receipt-scan',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Spreadsheet template',
    pageUrl: 'https://www.microsoft.com/en-us/microsoft-365/excel',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Google Drive - Tax folder',
    pageUrl: 'https://drive.google.com/drive/folders/tax-folder',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'OCR app',
    pageUrl: 'https://www.adobe.com/acrobat/online/ocr-pdf.html',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
]);

const guitarPairs = buildGoalPairs('practice guitar chords', [
  {
    pageTitle: 'JustinGuitar - Basic chords',
    pageUrl: 'https://www.justinguitar.com/guitar-lessons/basic-open-chords-b1-101',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Fender Play - Learn guitar',
    pageUrl: 'https://www.fender.com/play',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Guitar Tricks - Chord lesson',
    pageUrl: 'https://www.guitartricks.com/',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Ultimate Guitar - beginner chords',
    pageUrl: 'https://www.ultimate-guitar.com/',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Netflix - Trending Now',
    pageUrl: 'https://www.netflix.com/browse',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'ESPN - NBA Scores',
    pageUrl: 'https://www.espn.com/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Amazon home',
    pageUrl: 'https://www.amazon.com/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'YouTube - guitar chord lesson',
    pageUrl: 'https://www.youtube.com/watch?v=guitar-chords',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Metronome app',
    pageUrl: 'https://www.metronomeonline.com/',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Ear training app',
    pageUrl: 'https://www.teoria.com/',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Guitar Center sale',
    pageUrl: 'https://www.guitarcenter.com/',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'Shopping for gear, not practicing chords.',
  },
  {
    pageTitle: 'Guitar World interview with Slash',
    pageUrl: 'https://www.guitarworld.com/news/slash-interview',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Guitar Hero song list',
    pageUrl: 'https://guitarhero.fandom.com/wiki/Songs',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Acoustic guitar review article',
    pageUrl: 'https://www.musicradar.com/reviews/acoustic-guitars',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Chordify',
    pageUrl: 'https://chordify.net/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'MuseScore',
    pageUrl: 'https://musescore.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Tuner app',
    pageUrl: 'https://www.guitar-tuner.org/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Capo app',
    pageUrl: 'https://apps.apple.com/us/app/capo',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Notion - Practice log',
    pageUrl: 'https://www.notion.so/practice-log',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Spotify - guitar playlist',
    pageUrl: 'https://open.spotify.com/playlist/guitar',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
]);

const runningPairs = buildGoalPairs('train for a 10K run', [
  {
    pageTitle: 'Nike Run Club - 10K plan',
    pageUrl: 'https://www.nike.com/nrc-app',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Hal Higdon 10K training',
    pageUrl: 'https://www.halhigdon.com/training/10k-training/',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Strava training plan',
    pageUrl: 'https://www.strava.com/dashboard/training',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Couch to 10K app',
    pageUrl: 'https://www.c25k.com/10k',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'YouTube - gaming stream',
    pageUrl: 'https://www.youtube.com/watch?v=gamingstream',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Amazon home',
    pageUrl: 'https://www.amazon.com/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Home / X',
    pageUrl: 'https://x.com/home',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Garmin training status',
    pageUrl: 'https://connect.garmin.com/',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Runner\'s World - 10K pace chart',
    pageUrl: 'https://www.runnersworld.com/training/a20791976/10k-training-plan/',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'MapMyRun interval workout',
    pageUrl: 'https://www.mapmyrun.com/',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: '10-K annual report',
    pageUrl: 'https://www.sec.gov/edgar/search/#/q=10-k',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'Finance keyword collision with 10K.',
  },
  {
    pageTitle: 'Running shoe reviews on Reddit',
    pageUrl: 'https://www.reddit.com/r/running/comments/shoe_reviews',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Marathon expo tickets',
    pageUrl: 'https://www.eventbrite.com/e/marathon-expo',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Watch review article',
    pageUrl: 'https://www.cnet.com/tech/mobile/best-running-watches/',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Apple Health workout ring',
    pageUrl: 'https://www.apple.com/ios/health/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Google Calendar - run block',
    pageUrl: 'https://calendar.google.com/calendar/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Pace calculator',
    pageUrl: 'https://www.mcmillanrunning.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Hydration tracker',
    pageUrl: 'https://www.hydrateme.app/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Meetup running club',
    pageUrl: 'https://www.meetup.com/topics/running/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Strava route map',
    pageUrl: 'https://www.strava.com/routes',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
]);

const cameraPairs = buildGoalPairs('buy a used camera for travel photography', [
  {
    pageTitle: 'KEH - Used cameras',
    pageUrl: 'https://www.keh.com/shop/cameras.html',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'MPB - Camera listings',
    pageUrl: 'https://www.mpb.com/en-us',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'B&H - Used gear',
    pageUrl: 'https://www.bhphotovideo.com/c/browse/Used/ci/3720/N/4294547183',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Used mirrorless camera guide',
    pageUrl: 'https://www.digitalcameraworld.com/buying-guides/best-used-mirrorless-cameras',
    expectedLabel: 'on-task',
    category: 'clear',
  },
  {
    pageTitle: 'Netflix - Trending Now',
    pageUrl: 'https://www.netflix.com/browse',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Steam Store - Featured & Recommended Games',
    pageUrl: 'https://store.steampowered.com/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'Amazon home',
    pageUrl: 'https://www.amazon.com/',
    expectedLabel: 'off-task',
    category: 'clear',
  },
  {
    pageTitle: 'DPReview - Used camera guide',
    pageUrl: 'https://www.dpreview.com/buying-guides',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'YouTube - lens comparison',
    pageUrl: 'https://www.youtube.com/watch?v=lens-comparison',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Lightroom Classic tutorial',
    pageUrl: 'https://helpx.adobe.com/lightroom-classic/tutorials.html',
    expectedLabel: 'on-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Camera obscura history',
    pageUrl: 'https://www.britannica.com/technology/camera-obscura',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Security camera systems',
    pageUrl: 'https://www.safewise.com/home-security/cctv/',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Camera roll backup settings',
    pageUrl: 'https://support.apple.com/en-us/HT204264',
    expectedLabel: 'off-task',
    category: 'tricky',
    note: 'Phone settings, not gear shopping.',
  },
  {
    pageTitle: 'Camera lens repair forum',
    pageUrl: 'https://www.photrio.com/forum/',
    expectedLabel: 'off-task',
    category: 'tricky',
  },
  {
    pageTitle: 'Google Maps - photo spots',
    pageUrl: 'https://www.google.com/maps',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'TripAdvisor - scenic viewpoints',
    pageUrl: 'https://www.tripadvisor.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Pinterest - shot list',
    pageUrl: 'https://www.pinterest.com/',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Google Drive - gear checklist',
    pageUrl: 'https://drive.google.com/drive/folders/gear-checklist',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Notion - packing list',
    pageUrl: 'https://www.notion.so/packing-list',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
  {
    pageTitle: 'Lightroom catalog',
    pageUrl: 'https://www.adobe.com/products/photoshop-lightroom.html',
    expectedLabel: 'borderline',
    category: 'borderline',
  },
]);

export const THRESHOLD_PAIRS_EXPANDED: ThresholdPair[] = [
  ...biologyPairs,
  ...reactPairs,
  ...jobsPairs,
  ...climatePairs,
  ...spanishPairs,
  ...japanTripPairs,
  ...taxesPairs,
  ...guitarPairs,
  ...runningPairs,
  ...cameraPairs,
];
